# Site Settings
title: Edin Husić
#url: 'http://webjeda.com'
baseurl: 'https://zhero9.github.io' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Edin Husić 
#tagline: Full Stack Developer
pic: pic500.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Currently I am a postdoc at <a href="https://www.idsia.ch/" target="_defualt">IDSIA, Switzerland</a>
hosted by <a href="https://people.idsia.ch/~grandoni/" target="_defualt">Fabrizio Grandoni</a>. 
I am broadly interested in fundamental questions in algorithms 
and optimisation and especially for questions arising in algorithmic game theory and combinatorial optimisation.
You can find out more about me in 
<a href="cv.pdf" target="_blank"><b>CV</b></a> (December 2022). <br> <br>

I completed PhD in mathematics at the 
<a href="https://www.lse.ac.uk/mathematics/" target="_defualt">London School of Economics</a>
where I was fortunate to have
<a href="http://personal.lse.ac.uk/veghl/" target="_defualt">László Végh</a>
as my advisor.'

#sidebar links if you enter institution, you have to enter instutition site in instSite!
institution: 'IDSIA - USI/SUPSI'
instSite: 'https://www.idsia.ch/'
address: 'Via la Santa 1, 6962 Viganello, Switzerland'
scholar: 'citations?user=kJ2ZmxoAAAAJ&hl=en'
email: name . surname at supsi.ch
github: zhero9
quora: 'profile/Edin-Husić'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker#
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
