# Site Settings
title: Edin Husić
#url: 'http://webjeda.com'
baseurl: 'https://zhero9.github.io' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Edin Husić 
#tagline: Full Stack Developer
pic: pic500.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: I completed my PhD in mathematics at <a href="https://www.lse.ac.uk/Mathematics/About-Us" target="_defualt">London School of Economic</a>, 
where I was fortunate to have
<a href="http://personal.lse.ac.uk/veghl/" target="_defualt">László Végh</a> as my advisor. 
I am broadly interested in fundamental questions in algorithms and optimisation and especially for questions arrising in algorithmic game theory and combinatorial optimisation.
You can find out more about me in 
<a href="cv.pdf" target="_blank"><b>CV</b></a> (September 2021). 

#sidebar links if you enter institution, you have to enter instutition site in instSite!
institution: 'Department of Mathematics, London School of Economics and Political Science'
instSite: 'http://www.lse.ac.uk/Mathematics'
address: 'Houghton Street, London, WC2A 2AE, United Kingdom'
email: e.husic at lse.ac.uk
github: zhero9
quora: 'profile/Edin-Husić'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker#
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
